version: '3.1'

services:
  minio:
    image: minio/minio
    container_name: minio_s3
    ports:
      - "9000:9000"  # Acesso à interface web
      - "9001:9001"  # Acesso à API
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
